import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../../components/Header";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cyber & Cloud Service",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
